### ISSUE TITLE
How to retrain a new RL model in Town10

### ISSUE THREAD

**Issue by sonicokuo** [zhejz/carla-roach#26]
Dear zhejz,

I would like to use train_rl.sh to train a new model from scratch in Town10HD. I have changed the part of Town02 in endless_all.yaml into a Town10HD version, as the pattern shown below.

- env_id: Endless-v0
  env_configs:
    carla_map: Town10HD
    num_zombie_vehicles: [0, 100]
    num_zombie_walkers: [0, 200]
    weather_group: dynamic_1.0
  gpu: [0]

Besides, I have used the file carla_gym/utils/birdview_map.py to generate a new BEV hdf5 map of Town10, which is Town10HD.h5 in /maps. However, it report some errors as shown below

Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/hcis-s09/miniconda3/envs/carla/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/hcis-s09/miniconda3/envs/carla/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hcis-s09/miniconda3/envs/carla/lib/python3.7/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 13, in _worker
    env = env_fn_wrapper.var()
  File "train_rl.py", line 64, in <lambda>
    env = SubprocVecEnv([lambda config=config: env_maker(config) for config in server_manager.env_configs])
  File "train_rl.py", line 57, in env_maker
    seed=cfg.seed, no_rendering=True, **config['env_configs'])
  File "/home/hcis-s09/miniconda3/envs/carla/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/hcis-s09/miniconda3/envs/carla/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/hcis-s09/miniconda3/envs/carla/lib/python3.7/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/hcis-s09/Downloads/carla-roach/carla_gym/envs/suites/endless_env.py", line 9, in __init__
    obs_configs, reward_configs, terminal_configs, all_tasks)
  File "/home/hcis-s09/Downloads/carla-roach/carla_gym/carla_multi_agent_env.py", line 28, in __init__
    self._init_client(carla_map, host, port, seed=seed, no_rendering=no_rendering)
  File "/home/hcis-s09/Downloads/carla-roach/carla_gym/carla_multi_agent_env.py", line 152, in _init_client
    self._world = client.load_world(carla_map)
RuntimeError: time-out of 60000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000

I guess that just changing the town name from Town02 to Town10HD in endless_all.yaml is not sufficient enough to change the target town of RL training.
Could you please give me some hints about how to retrain a new RL model in Town10?
Thank you all for all of your beautiful works!

Sincerely,
sonicokuo

**Comment by zhejz** [comment]
It seems to be a problem from the CARLA server side.

**Comment by Z7MightGuy** [comment]
@sonicokuo Hey, were you able to solve this issue? Also, could you run a benchmark test on town 10?

**Comment by zhejz** [comment]
This issue is most likely related to CARLA rather than our code.
I recommend posting it on the CARLA GitHub repository.
