### ISSUE TITLE
train_rl 

### ISSUE THREAD

**Issue by W981226** [zhejz/carla-roach#29]
hello，When I execute `run/train_rl.sh`, I encountered the following problems:
`Traceback (most recent call last):
  File "train_rl.py", line 62, in main
    env = DummyVecEnv([lambda config=config: env_maker(config) for config in server_manager.env_configs])
  File "/home/whm/anaconda3/envs/roach/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 23, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/whm/anaconda3/envs/roach/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 23, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "train_rl.py", line 62, in <lambda>
    env = DummyVecEnv([lambda config=config: env_maker(config) for config in server_manager.env_configs])
  File "train_rl.py", line 58, in env_maker
    env = EnvWrapper(env, **wrapper_kargs)
  File "/home/whm/roach/agents/rl_birdview/utils/rl_birdview_wrapper.py", line 25, in __init__
    assert len(env._obs_configs) == 1
  File "/home/whm/anaconda3/envs/roach/lib/python3.8/site-packages/gym/core.py", line 228, in __getattr__
    raise AttributeError(f"attempted to get missing private attribute '{name}'")
AttributeError: attempted to get missing private attribute '_obs_configs`

 what's the issue?

**Comment by zhejz** [comment]
Closing stale issue.
