### ISSUE TITLE
About Starting Carla 

### ISSUE THREAD

**Issue by Lesliewsq** [zhejz/carla-roach#33]
CARLA version: 0.9.10
Platform/OS: Ubuntu 22.04
CUDA ：12.2
When I run these two commands, I encounter an error, and it may have caused me to be unable to start the Carla Simulator. Calling for help.
```
bash /home/tech/carla/CarlaUE4.sh
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen

```
```
./run/train_rl.sh 
CarlaUE4-Linux: 未找到进程
[2023-09-11 11:41:53,139][utils.server_utils][INFO] - Kill Carla Servers!
CarlaUE4-Linux: 未找到进程
[2023-09-11 11:41:54,156][utils.server_utils][INFO] - Kill Carla Servers!
[2023-09-11 11:41:54,156][utils.server_utils][INFO] - SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=1 bash /home/njtech/carla/CarlaUE4.sh -fps=10 -quality-level=Epic -carla-rpc-port=2000
[2023-09-11 11:41:54,161][utils.server_utils][INFO] - SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=1 bash /home/njtech/carla/CarlaUE4.sh -fps=10 -quality-level=Epic -carla-rpc-port=2005
[2023-09-11 11:41:54,165][utils.server_utils][INFO] - SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=1 bash /home/njtech/carla/CarlaUE4.sh -fps=10 -quality-level=Epic -carla-rpc-port=2010
[2023-09-11 11:41:54,168][utils.server_utils][INFO] - SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=1 bash /home/njtech/carla/CarlaUE4.sh -fps=10 -quality-level=Epic -carla-rpc-port=2015
[2023-09-11 11:41:54,171][utils.server_utils][INFO] - SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=1 bash /home/njtech/carla/CarlaUE4.sh -fps=10 -quality-level=Epic -carla-rpc-port=2020
[2023-09-11 11:41:54,174][utils.server_utils][INFO] - SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=1 bash /home/njtech/carla/CarlaUE4.sh -fps=10 -quality-level=Epic -carla-rpc-port=2025
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
4.24.3-0+++UE4+Release-4.24 518 0
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Disabling core dumps.
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
[2023-09-11 11:42:01,081][agents.rl_birdview.rl_birdview_agent][INFO] - Resume checkpoint latest ckpt/ckpt_6082560.pth
[2023-09-11 11:42:05,036][agents.rl_birdview.rl_birdview_agent][INFO] - Loading wandb checkpoint: ckpt/ckpt_6082560.pth
carla_map load_world(): Town02
carla_map load_world(): Town05
carla_map load_world(): Town04
carla_map load_world(): Town06
carla_map load_world(): Town01
carla_map load_world(): Town03
Traceback (most recent call last):
  File "train_rl.py", line 64, in main
    env = SubprocVecEnv([lambda config=config: env_maker(config) for config in server_manager.env_configs])
  File "/home/njtech/anaconda3/envs/carla/lib/python3.7/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 98, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/njtech/anaconda3/envs/carla/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/njtech/anaconda3/envs/carla/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/njtech/anaconda3/envs/carla/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2023-09-11 11:43:07,615][wandb.sdk.internal.internal][INFO] - Internal process exited
 PYTHON_RETURN=0!!! Start Over!!!
CarlaUE4-Linux: 未找到进程
Bash script done.
```

**Comment by zhejz** [comment]
Since it is about CARLA, I'd suggest to raise this issue in the CARLA github repo ([here](https://github.com/carla-simulator/carla)) where you should get more helps.
